-- Ziarem CRM – database structure
-- Lookup tables (from Data Dictionaries) + main leads table (FA + CP Data Appended).

-- ========== LOOKUP TABLES ==========
-- Map from Occupation.csv + Occupation Code.csv
CREATE TABLE dict_occupations (
  code        VARCHAR(50) PRIMARY KEY,
  description TEXT NOT NULL
);

-- Map from DOC_TYPE.csv
CREATE TABLE dict_doc_types (
  code        VARCHAR(50) PRIMARY KEY,
  description TEXT NOT NULL
);

-- Map from PROP_CL_IND.csv
CREATE TABLE dict_property_class (
  code        VARCHAR(50) PRIMARY KEY,
  description TEXT NOT NULL
);

-- ========== MAIN TABLE: leads (FA + CP Data Appended columns) ==========
CREATE TABLE leads (
  autoId_ui BIGINT PRIMARY KEY,
  ID_Individuals BIGINT,
  mobile_ui VARCHAR(50),
  hh VARCHAR(1),
  first_name VARCHAR(255),
  middle_init VARCHAR(255),
  last_name VARCHAR(255),
  name_suffix VARCHAR(255),
  DOB DATE,
  gender_cd VARCHAR(50),
  address_1 VARCHAR(255),
  city VARCHAR(255),
  state VARCHAR(255),
  zip_code VARCHAR(255),
  zip_cd_4 VARCHAR(255),
  phone_nbr VARCHAR(255),
  mobile_phone VARCHAR(255),
  email_addr VARCHAR(255),
  home_owner_flag VARCHAR(1),
  home_value NUMERIC(15),
  home_market_value NUMERIC(15),
  length_of_residence VARCHAR(255),
  credit_rating VARCHAR(255),
  auto_xdate DATE,
  auto_xdate_source DATE,
  trans_dt_1 DATE,
  year_1 INTEGER,
  make_1 VARCHAR(255),
  model_1 VARCHAR(255),
  vin_1 VARCHAR(255),
  boat VARCHAR(255),
  motorcycle VARCHAR(255),
  RV VARCHAR(255),
  hispanic VARCHAR(255),
  lat DOUBLE PRECISION,
  lon DOUBLE PRECISION,
  trans_dt_2 DATE,
  year_2 INTEGER,
  make_2 VARCHAR(255),
  model_2 VARCHAR(255),
  vin_2 VARCHAR(255),
  trans_dt_3 DATE,
  year_3 INTEGER,
  make_3 VARCHAR(255),
  model_3 VARCHAR(255),
  vin_3 VARCHAR(255),
  trans_dt_4 DATE,
  year_4 INTEGER,
  make_4 VARCHAR(255),
  model_4 VARCHAR(255),
  vin_4 VARCHAR(255),
  mobile_dnc_flag VARCHAR(1),
  landline_dnc_flag VARCHAR(1),
  ip_addr VARCHAR(255),
  dwelling_type VARCHAR(255),
  ValidationCode VARCHAR(255),
  phone_match_type VARCHAR(255),
  mobile_match_type VARCHAR(255),
  email_match_type VARCHAR(255),
  source_code VARCHAR(255),
  mobile_conf_cd VARCHAR(50),
  aerobics VARCHAR(255),
  AirConditioning VARCHAR(255),
  art_craft VARCHAR(255),
  auto_motorcycle_racing VARCHAR(255),
  auto_parts_repair_accesories_work VARCHAR(255),
  auto_work VARCHAR(255),
  avid_readers VARCHAR(255),
  bank_card VARCHAR(255),
  baseball VARCHAR(255),
  basketball VARCHAR(255),
  BookBuyer VARCHAR(255),
  camping_or_hiking VARCHAR(255),
  career_minded VARCHAR(255),
  carrier_route VARCHAR(255),
  Carrier_Route_Type VARCHAR(255),
  cars VARCHAR(255),
  casino_gambling VARCHAR(255),
  cc_premium_american_express VARCHAR(255),
  cc_premium_discover VARCHAR(255),
  cc_premium_store_or_retail VARCHAR(255),
  cc_premium_visa_or_mastercard VARCHAR(255),
  cc_regular_american_express VARCHAR(255),
  cc_regular_discover VARCHAR(255),
  cc_regular_store_or_retail VARCHAR(255),
  Collect_SpecialFoodsBuyer VARCHAR(255),
  collector_antiques VARCHAR(255),
  collector_coins VARCHAR(255),
  collector_dolls VARCHAR(255),
  collector_figurines VARCHAR(255),
  collector_fine_arts VARCHAR(255),
  collector_music VARCHAR(255),
  collector_plates DOUBLE PRECISION,
  collector_sports_memorabilia VARCHAR(255),
  collector_stamps VARCHAR(255),
  collectors VARCHAR(255),
  consumer_electronics VARCHAR(255),
  contribute_animal VARCHAR(255),
  contribute_childrens VARCHAR(255),
  contribute_environm VARCHAR(255),
  contribute_health VARCHAR(255),
  contribute_political VARCHAR(255),
  contribute_political_conservative VARCHAR(255),
  contribute_political_liberal VARCHAR(255),
  contribute_religious VARCHAR(255),
  contribute_veterans VARCHAR(255),
  contributor_index VARCHAR(255),
  contributors VARCHAR(255),
  Crafts_HobbMerchBuyer VARCHAR(255),
  credit_card VARCHAR(255),
  credit_cards_regular_visa_or_mastercard VARCHAR(255),
  creditcard_newissue VARCHAR(255),
  cultural_artistic VARCHAR(255),
  curr_home_value NUMERIC(15),
  current_affairs_politics VARCHAR(255),
  diet_weight_loss VARCHAR(255),
  doit_yourselfer VARCHAR(255),
  donor_arts_or_cultural VARCHAR(255),
  education_code VARCHAR(255),
  entertainment_enth VARCHAR(255),
  family VARCHAR(255),
  family_position VARCHAR(255),
  FemaleMerchBuyer VARCHAR(255),
  fishing VARCHAR(255),
  fitness VARCHAR(255),
  food VARCHAR(255),
  football VARCHAR(255),
  gardening VARCHAR(255),
  gen_in_household VARCHAR(255),
  genre_musictype_christian_or_gospel VARCHAR(255),
  genre_musictype_classical VARCHAR(255),
  genre_musictype_country VARCHAR(255),
  genre_musictype_jazz VARCHAR(255),
  genre_musictype_rhythm_and_blues VARCHAR(255),
  genre_musictype_rock_n_roll VARCHAR(255),
  genre_musictype_soft_rock_or_easy_listen VARCHAR(255),
  golf VARCHAR(255),
  great_outdoors VARCHAR(255),
  health_beauty VARCHAR(255),
  health_living VARCHAR(255),
  HighTechLeader VARCHAR(255),
  hobby_bird_watching VARCHAR(255),
  hobby_board_games VARCHAR(255),
  hobby_computer_games VARCHAR(255),
  hobby_cigar_smoking VARCHAR(255),
  hobby_cooking VARCHAR(255),
  hobby_cooking_gourmet VARCHAR(255),
  hobby_crafts VARCHAR(255),
  hobby_home_study_courses VARCHAR(255),
  hobby_knitting_or_needlework VARCHAR(255),
  hobby_photography VARCHAR(255),
  hobby_quilting VARCHAR(255),
  hobby_self_improvement_courses VARCHAR(255),
  hobby_sewing VARCHAR(255),
  hobby_video_games VARCHAR(255),
  hobby_wine_appreciation VARCHAR(255),
  hobby_woodworking VARCHAR(255),
  Hobbyists VARCHAR(255),
  hockey VARCHAR(255),
  home_decor VARCHAR(255),
  HomeHeatIndicator VARCHAR(255),
  hunting VARCHAR(255),
  income NUMERIC(15),
  internet_buyer VARCHAR(255),
  Investment_type VARCHAR(255),
  investments VARCHAR(255),
  investments_own_mutual_funds_cds VARCHAR(255),
  investments_own_stocks_or_bonds VARCHAR(255),
  language VARCHAR(255),
  luxury_life VARCHAR(255),
  magazine VARCHAR(255),
  mail_buyer VARCHAR(255),
  mail_donor VARCHAR(255),
  mail_responder VARCHAR(255),
  MaleMerchBuyer VARCHAR(255),
  marital_status VARCHAR(255),
  median_home_value NUMERIC(15),
  median_income NUMERIC(15),
  membership_warehouse VARCHAR(255),
  mo_books VARCHAR(255),
  mo_books_or_mag VARCHAR(255),
  mo_children_s_products VARCHAR(255),
  mo_clothing VARCHAR(255),
  mo_cosmetics VARCHAR(255),
  mo_dvd VARCHAR(255),
  mo_gifts VARCHAR(255),
  mo_home_furnishing VARCHAR(255),
  mo_jewelry VARCHAR(255),
  mo_plus_size_clothing VARCHAR(255),
  movie VARCHAR(255),
  music VARCHAR(255),
  musical_instruments VARCHAR(255),
  music_player VARCHAR(255),
  nascar VARCHAR(255),
  net_worth NUMERIC(15),
  new_credit_range VARCHAR(255),
  num_credit_lines VARCHAR(255),
  occupation VARCHAR(255),
  occupation_code VARCHAR(255),
  online_education VARCHAR(255),
  opportunity_seeker VARCHAR(255),
  own_swimming_pool VARCHAR(255),
  owns_satellite_tv VARCHAR(255),
  pets VARCHAR(255),
  pets_own_at_least_one_cat VARCHAR(255),
  pets_own_at_least_one_dog VARCHAR(255),
  presence_of_elderly_parent VARCHAR(255),
  PresenceofGoldOrPlatinumCreditCard DOUBLE PRECISION,
  presence_premium_card VARCHAR(255),
  race VARCHAR(255),
  reading_news_finance VARCHAR(255),
  reading_astrology VARCHAR(255),
  reading_best_selling_fiction VARCHAR(255),
  reading_bible_or_devotional VARCHAR(255),
  reading_books_on_tape VARCHAR(255),
  reading_computer VARCHAR(255),
  reading_cooking_or_culinary VARCHAR(255),
  reading_country_lifestyle VARCHAR(255),
  reading_fashion VARCHAR(255),
  reading_history VARCHAR(255),
  reading_interior_decorating VARCHAR(255),
  reading_medical_or_health VARCHAR(255),
  reading_military VARCHAR(255),
  reading_mystery VARCHAR(255),
  reading_natural_health_remedies VARCHAR(255),
  reading_people_or_entertainment VARCHAR(255),
  reading_romance VARCHAR(255),
  reading_science_fiction VARCHAR(255),
  reading_science_or_technology VARCHAR(255),
  reading_sports VARCHAR(255),
  reading_world_news_or_politics VARCHAR(255),
  religious_inspirational VARCHAR(255),
  residental_properties_owned VARCHAR(255),
  RespondedtoCatalog VARCHAR(255),
  retail_card VARCHAR(255),
  running VARCHAR(255),
  science_space VARCHAR(255),
  scuba_diving VARCHAR(255),
  self_improvement VARCHAR(255),
  snow_skiing VARCHAR(255),
  soho_business VARCHAR(255),
  sporting_life VARCHAR(255),
  sports VARCHAR(255),
  sports_betting VARCHAR(255),
  sweepstakes_contest VARCHAR(255),
  tennis VARCHAR(255),
  travel VARCHAR(255),
  travel_business VARCHAR(255),
  travel_card VARCHAR(255),
  travel_cruises VARCHAR(255),
  travel_international VARCHAR(255),
  travel_personal VARCHAR(255),
  travel_vacation VARCHAR(255),
  truck_owner VARCHAR(255),
  tv_sports VARCHAR(255),
  ValueHunter NUMERIC(15),
  veteran_in_household VARCHAR(255),
  voter_indicator VARCHAR(255),
  walking VARCHAR(255),
  WealthRating VARCHAR(255),
  weight_lifting VARCHAR(255),
  working_woman VARCHAR(255),
  young_adult_in_household VARCHAR(255),
  Soccer VARCHAR(255),
  FIPS VARCHAR(255),
  prop_cl_ind VARCHAR(255),
  LandUseCode VARCHAR(255),
  MobileHomeInd VARCHAR(255),
  LotSizeFrontageFeet VARCHAR(255),
  LotSizeDepthFeet VARCHAR(255),
  LotSizeAcres VARCHAR(255),
  LotSizeSqFt VARCHAR(255),
  AssdTotalValue NUMERIC(15),
  BuildingAreaInd VARCHAR(255),
  SumBuildingSqFt VARCHAR(255),
  SumLivingAreaSqFt VARCHAR(255),
  SumGroundFloorSqFt VARCHAR(255),
  SumGrossAreaSqFt VARCHAR(255),
  SumAdjAreaSqFt VARCHAR(255),
  SumBasementSqFt VARCHAR(255),
  BasementUnfinishedSqFt VARCHAR(255),
  BasementFinishedSqFt VARCHAR(255),
  SumGarageSqFt VARCHAR(255),
  YearBuilt INTEGER,
  EffectiveYearBuilt INTEGER,
  Bedrooms VARCHAR(255),
  TotalRooms VARCHAR(255),
  BathTotalCalc VARCHAR(255),
  BasementCode VARCHAR(255),
  BuildingConditionCode VARCHAR(255),
  ExteriorWallsCode VARCHAR(255),
  FireplaceCode VARCHAR(255),
  FloorCoverCode VARCHAR(255),
  Garage VARCHAR(255),
  HeatCode VARCHAR(255),
  HeatingFuelTypeCode VARCHAR(255),
  GarageParkingNbr VARCHAR(255),
  PoolCode VARCHAR(255),
  RoofCoverCode VARCHAR(255),
  RoofTypeCode VARCHAR(255),
  SewerCode VARCHAR(255),
  StoriesNbrCode VARCHAR(255),
  StyleCode VARCHAR(255),
  SumResidentialUnits VARCHAR(255),
  WaterCode VARCHAR(255),
  SubdivisionName VARCHAR(255),
  SubdivisionTractNbr VARCHAR(255),
  CurrentSaleDocNbr VARCHAR(255),
  CurrentSaleRecordingDate DATE,
  CurrentSaleContractDate DATE,
  doc_type_code VARCHAR(255),
  CurrentSalesPrice NUMERIC(15),
  DatafuseCode VARCHAR(255),
  MD_ParsedAddressRange VARCHAR(255),
  MD_ParsedPreDirection VARCHAR(255),
  MD_ParsedStreetName VARCHAR(255),
  MD_ParsedSuffix VARCHAR(255),
  MD_ParsedPostDirection VARCHAR(255),
  MD_ParsedSuiteName VARCHAR(255),
  MD_ParsedSuiteRange VARCHAR(255),
  address_type VARCHAR(255),
  address_2 VARCHAR(255),
  census_block VARCHAR(255),
  census_tract VARCHAR(255),
  county_code VARCHAR(255),
  county_name VARCHAR(255),
  DeedDateofRefinance DATE,
  delivery_point VARCHAR(255),
  dpv_status VARCHAR(255),
  email_flag VARCHAR(1),
  MortgageAmountinThousands NUMERIC(15),
  MortgageAmountinThousandsCode NUMERIC(15),
  Mortgageloantype VARCHAR(255),
  num_in_household VARCHAR(255),
  num_of_adults VARCHAR(255),
  num_of_children VARCHAR(255),
  Number_Of_Bathrooms VARCHAR(255),
  Number_Of_Bedrooms VARCHAR(255),
  political VARCHAR(255),
  purchase_2nd_mortgage_amount NUMERIC(15),
  purchase_2nd_mortgage_loan_type VARCHAR(255),
  purchase_lender_code VARCHAR(255),
  purchase_mortgage_date DATE,
  recent_2nd_lender_code VARCHAR(255),
  recent_2nd_Lender_name VARCHAR(255),
  recent_2nd_mortgage_amount NUMERIC(15),
  recent_2nd_mortgage_date DATE,
  recent_2nd_mortgage_interest_rate VARCHAR(255),
  recent_2nd_mortgage_interest_rate_type VARCHAR(255),
  recent_2nd_mortgage_loan_type VARCHAR(255),
  recent_lender_code VARCHAR(255),
  recent_mortgage_interest_rate VARCHAR(255),
  RefinanceAmountinThousands NUMERIC(15),
  RefinanceAmountinThousandsCode NUMERIC(15),
  RefinanceLoanType VARCHAR(255),
  RefinanceRateType VARCHAR(255),
  religion VARCHAR(255),
  FirstMtgTerm VARCHAR(255),
  FirstMtgTermCode VARCHAR(255),
  FirstMtgInterestRateType VARCHAR(255),
  FirstMtgDueDate DATE,
  OwnerOccupied VARCHAR(255),
  TaxAmt VARCHAR(255),
  TaxYear INTEGER,
  ziarem_tags JSONB,
  enrichment_result JSONB
);

-- Indexes for fast searching
CREATE INDEX idx_leads_zip ON leads (zip_code);
CREATE INDEX idx_leads_last_name ON leads (last_name);
CREATE INDEX idx_leads_occupation_code ON leads (occupation_code);
CREATE INDEX idx_leads_doc_type_code ON leads (doc_type_code);

-- Foreign Keys (allow NULLs)
ALTER TABLE leads ADD CONSTRAINT fk_leads_occupation_code
  FOREIGN KEY (occupation_code) REFERENCES dict_occupations(code) ON DELETE SET NULL;

ALTER TABLE leads ADD CONSTRAINT fk_leads_doc_type_code
  FOREIGN KEY (doc_type_code) REFERENCES dict_doc_types(code) ON DELETE SET NULL;

ALTER TABLE leads ADD CONSTRAINT fk_leads_prop_cl_ind
  FOREIGN KEY (prop_cl_ind) REFERENCES dict_property_class(code) ON DELETE SET NULL;

COMMENT ON TABLE leads IS 'Ziarem CRM main lead table (~1M rows). FA + CP Data Appended columns + ziarem_tags (Wolf/Dispute/Lyco).';
