/**
 * FA + CP Data Appended column names from Cole Data Dictionary (FA + CP Data Appended sheet).
 * Used to build FA + CP Data Appended.csv when the xlsx is exported to CSV (Column_name, Type, Length).
 */
module.exports = [
  'ID_Individuals', 'autoId_ui#', 'mobile_ui#', 'hh', 'first_name', 'middle_init', 'last_name', 'name_suffix',
  'DOB', 'gender_cd', 'address_1', 'city', 'state', 'zip_code', 'zip_cd_4', 'phone_nbr', 'mobile_phone', 'email_addr',
  'home_owner_flag', 'home_value', 'length_of_residence', 'credit_rating', 'auto_xdate', 'auto_xdate_source',
  'trans_dt_1', 'year_1', 'make_1', 'model_1', 'vin_1', 'boat', 'motorcycle', 'RV', 'hispanic', 'lat', 'lon',
  'trans_dt_2', 'year_2', 'make_2', 'model_2', 'vin_2', 'trans_dt_3', 'year_3', 'make_3', 'model_3', 'vin_3',
  'trans_dt_4', 'year_4', 'make_4', 'model_4', 'vin_4', 'mobile_dnc_flag', 'landline_dnc_flag', 'ip_addr', 'dwelling_type',
  'ValidationCode', 'phone_match_type', 'mobile_match_type', 'email_match_type', 'source_code', 'mobile_conf_cd',
  'aerobics', 'AirConditioning', 'art_craft', 'auto_motorcycle_racing', 'auto_parts_repair_accesories_work', 'auto_work',
  'avid_readers', 'bank_card', 'baseball', 'basketball', 'BookBuyer', 'camping_or_hiking', 'career_minded', 'carrier_route', 'Carrier_Route_Type', 'cars',
  'casino_gambling', 'cc_premium_american_express', 'cc_premium_discover', 'cc_premium_store_or_retail', 'cc_premium_visa_or_mastercard',
  'cc_regular_american_express', 'cc_regular_discover', 'cc_regular_store_or_retail', 'Collect_SpecialFoodsBuyer', 'collector_antiques',
  'collector_coins', 'collector_dolls', 'collector_figurines', 'collector_fine_arts', 'collector_music', 'collector_plates',
  'collector_sports_memorabilia', 'collector_stamps', 'collectors', 'consumer_electronics', 'contribute_animal', 'contribute_childrens',
  'contribute_environm', 'contribute_health', 'contribute_political', 'contribute_political_conservative', 'contribute_political_liberal',
  'contribute_religious', 'contribute_veterans', 'contributor_index', 'contributors', 'Crafts_HobbMerchBuyer', 'credit_card',
  'credit_cards_regular_visa_or_mastercard', 'creditcard_newissue', 'cultural_artistic', 'curr_home_value', 'current_affairs_politics',
  'diet_weight_loss', 'doit_yourselfer', 'donor_arts_or_cultural', 'education_code', 'entertainment_enth', 'family', 'family_position',
  'FemaleMerchBuyer', 'fishing', 'fitness', 'food', 'football', 'gardening', 'gen_in_household', 'genre_musictype_christian_or_gospel',
  'genre_musictype_classical', 'genre_musictype_country', 'genre_musictype_jazz', 'genre_musictype_rhythm_and_blues', 'genre_musictype_rock_n_roll',
  'genre_musictype_soft_rock_or_easy_listen', 'golf', 'great_outdoors', 'health_beauty', 'health_living', 'HighTechLeader', 'hobby_bird_watching',
  'hobby_board_games', 'hobby_computer_games', 'hobby_cigar_smoking', 'hobby_cooking', 'hobby_cooking_gourmet', 'hobby_crafts',
  'hobby_home_study_courses', 'hobby_knitting_or_needlework', 'hobby_photography', 'hobby_quilting', 'hobby_self_improvement_courses',
  'hobby_sewing', 'hobby_video_games', 'hobby_wine_appreciation', 'hobby_woodworking', 'Hobbyists', 'hockey', 'home_decor', 'HomeHeatIndicator',
  'hunting', 'income', 'internet_buyer', 'Investment_type', 'investments', 'investments_own_mutual_funds_cds', 'investments_own_stocks_or_bonds',
  'language', 'luxury_life', 'magazine', 'mail_buyer', 'mail_donor', 'mail_responder', 'MaleMerchBuyer', 'marital_status', 'median_home_value',
  'median_income', 'membership_warehouse', 'mo_books', 'mo_books_or_mag', 'mo_children_s_products', 'mo_clothing', 'mo_cosmetics', 'mo_dvd',
  'mo_gifts', 'mo_home_furnishing', 'mo_jewelry', 'mo_plus_size_clothing', 'movie', 'music', 'musical_instruments', 'music_player', 'nascar',
  'net_worth', 'new_credit_range', 'num_credit_lines', 'occupation', 'occupation_code', 'online_education', 'opportunity_seeker', 'own_swimming_pool',
  'owns_satellite_tv', 'pets', 'pets_own_at_least_one_cat', 'pets_own_at_least_one_dog', 'presence_of_elderly_parent',
  'PresenceofGoldOrPlatinumCreditCard', 'presence_premium_card', 'race', 'reading_news_finance', 'reading_astrology', 'reading_best_selling_fiction',
  'reading_bible_or_devotional', 'reading_books_on_tape', 'reading_computer', 'reading_cooking_or_culinary', 'reading_country_lifestyle', 'reading_fashion',
  'reading_history', 'reading_interior_decorating', 'reading_medical_or_health', 'reading_military', 'reading_mystery', 'reading_natural_health_remedies',
  'reading_people_or_entertainment', 'reading_romance', 'reading_science_fiction', 'reading_science_or_technology', 'reading_sports',
  'reading_world_news_or_politics', 'religious_inspirational', 'residental_properties_owned', 'RespondedtoCatalog', 'retail_card', 'running',
  'science_space', 'scuba_diving', 'self_improvement', 'snow_skiing', 'soho_business', 'sporting_life', 'sports', 'sports_betting', 'sweepstakes_contest',
  'tennis', 'travel', 'travel_business', 'travel_card', 'travel_cruises', 'travel_international', 'travel_personal', 'travel_vacation', 'truck_owner',
  'tv_sports', 'ValueHunter', 'veteran_in_household', 'voter_indicator', 'walking', 'WealthRating', 'weight_lifting', 'working_woman',
  'young_adult_in_household', 'Soccer', 'FIPS', 'PropertyClassID', 'LandUseCode', 'MobileHomeInd', 'LotSizeFrontageFeet', 'LotSizeDepthFeet',
  'LotSizeAcres', 'LotSizeSqFt', 'AssdTotalValue', 'BuildingAreaInd', 'SumBuildingSqFt', 'SumLivingAreaSqFt', 'SumGroundFloorSqFt', 'SumGrossAreaSqFt',
  'SumAdjAreaSqFt', 'SumBasementSqFt', 'BasementUnfinishedSqFt', 'BasementFinishedSqFt', 'SumGarageSqFt', 'YearBuilt', 'EffectiveYearBuilt', 'Bedrooms',
  'TotalRooms', 'BathTotalCalc', 'BasementCode', 'BuildingConditionCode', 'ExteriorWallsCode', 'FireplaceCode', 'FloorCoverCode', 'Garage', 'HeatCode',
  'HeatingFuelTypeCode', 'GarageParkingNbr', 'PoolCode', 'RoofCoverCode', 'RoofTypeCode', 'SewerCode', 'StoriesNbrCode', 'StyleCode', 'SumResidentialUnits',
  'WaterCode', 'SubdivisionName', 'SubdivisionTractNbr', 'CurrentSaleDocNbr', 'CurrentSaleRecordingDate', 'CurrentSaleContractDate', 'CurrentSaleDocumentType',
  'CurrentSalesPrice', 'DatafuseCode', 'MD_ParsedAddressRange', 'MD_ParsedPreDirection', 'MD_ParsedStreetName', 'MD_ParsedSuffix', 'MD_ParsedPostDirection',
  'MD_ParsedSuiteName', 'MD_ParsedSuiteRange', 'Address Type', 'address_2', 'census_block', 'census_tract', 'county_code', 'county_name',
  'DeedDateofRefinance', 'delivery_point', 'dpv_status', 'email_flag', 'MortgageAmountinThousands', 'MortgageAmountinThousandsCode', 'Mortgageloantype',
  'num_in_household', 'num_of_adults', 'num_of_children', 'Number_Of_Bathrooms', 'Number_Of_Bedrooms', 'political', 'purchase_2nd_mortgage_amount',
  'purchase_2nd_mortgage_loan_type', 'purchase_lender_code', 'purchase_mortgage_date', 'recent_2nd_lender_code', 'recent_2nd_Lender_name',
  'recent_2nd_mortgage_amount', 'recent_2nd_mortgage_date', 'recent_2nd_mortgage_interest_rate', 'recent_2nd_mortgage_interest_rate_type',
  'recent_2nd_mortgage_loan_type', 'recent_lender_code', 'recent_mortgage_interest_rate', 'RefinanceAmountinThousands', 'RefinanceAmountinThousandsCode',
  'RefinanceLoanType', 'RefinanceRateType', 'religion', 'FirstMtgTerm', 'FirstMtgTermCode', 'FirstMtgInterestRateType', 'FirstMtgDueDate', 'OwnerOccupied',
  'TaxAmt', 'TaxYear'
];
